#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run lint-staged

# npm run build ||
# (
#     echo '❌👷🔨❌ Better call Leo... Because your build failed ❌👷🔨❌
#             Build failed: View the errors above to see why.
#     '
#     false;
# )

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
